@startuml UC02 - Registrar Não Conformidade
title UC02 - Registrar Não Conformidade (Atividades)

start
:Identificar status NOK;
:Solicitar motivo da reprovação;
:Selecionar motivo ou digitar observação;
:Vincular motivo ao registro da inspeção;
:Salvar dados no banco de dados;
stop
@enduml
